[package]
name = "ably"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "*" }
atty = { version = "*" }
base64 = { version = "*" }
block-modes = { version = "*" }
cipher = { version = "*" }
chrono = { version = "*", features = ["serde"] }
dyn-clone = { version = "*" }
futures = { version = "*" }
hmac = { version = "*" }
lazy_static = { version = "*" }
log = { version = "*" }
mime = { version = "*" }
rand = { version = "*" }
regex = { version = "*" }
reqwest = { version = "*", features = ["json"] }
rmp-serde = { version = "*" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { version = "*" }
serde_json = { version = "*" }
serde_repr = { version = "*" }
sha2 = { version = "*" }
simplelog = { version = "*" }
url = { version = "*" }

[dev-dependencies]
tokio = { version = "*", features = ["macros"] }
