[package]
name = "ably"
version = "0.1.0"
authors = ["Lewis Marshall <lewis.marshall@ably.com>"]
edition = "2018"
description = "Ably client library SDK"
documentation = "https://docs.rs/ably"
readme = "README.md"
homepage = "https://ably.com"
repository = "https://github.com/ably-labs/ably-rust"
license = "Apache-2.0"
keywords = ["ably", "realtime", "pubsub"]

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
]

[dependencies]
aes = { version = "*" }
atty = { version = "*" }
base64 = { version = "*" }
block-modes = { version = "*" }
cipher = { version = "*" }
chrono = { version = "*", features = ["serde"] }
dyn-clone = { version = "*" }
futures = { version = "*" }
hmac = { version = "*" }
lazy_static = { version = "*" }
log = { version = "*" }
mime = { version = "*" }
rand = { version = "*" }
regex = { version = "*" }
reqwest = { version = "*", features = ["json"] }
rmp-serde = { version = "*" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { version = "*" }
serde_json = { version = "*" }
serde_repr = { version = "*" }
sha2 = { version = "*" }
simplelog = { version = "*" }
url = { version = "*" }

[dev-dependencies]
tokio = { version = "*", features = ["full"] }

[[example]]
name = "publish"
path = "examples/publish.rs"

[[example]]
name = "history"
path = "examples/history.rs"

[[example]]
name = "encrypt"
path = "examples/encrypt.rs"
